import { TanstackReactQueryProvider } from "@/lib/api";
import { AuthProvider } from "@/modules/auth/context/AuthContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	const token = cookieStore.get("access_token")?.value || "";
	const isAuthenticated = !!token;
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<TanstackReactQueryProvider>
					<AuthProvider initialAuth={isAuthenticated}>{children}</AuthProvider>
				</TanstackReactQueryProvider>
			</body>
		</html>
	);
}
