from typing import Dict, List

data: Dict[str, List[str]] = {
    "Quaid-e-Azam": [
        "Muhammad Ali Jinnah",
        "Quaid-e-Azam",
        "Quaid-e-Azam Muhammad Ali Jinnah, the founder of Pakistan, is remembered as one of the greatest leaders of the 20th century. Born on December 25, 1876, in Karachi, he became a lawyer, politician, and visionary statesman who dedicated his life to the cause of Muslims in the Indian subcontinent.",
        "Jinnah was born in a respected merchant family. His father, Jinnahbhai Poonja, was a successful businessman. This supportive family environment helped him pursue education and later his political career.",
        "Jinnah received his early education in Karachi and Bombay. At the age of 16, he went to London and studied law at Lincoln’s Inn. His exposure to Western education and politics shaped his vision of democracy, justice, and equality.",
        "After returning to India, Jinnah started practicing law in Bombay. He gained fame as one of the most successful lawyers of his time, known for his sharp intellect, logical arguments, and strong command over English.",
        "In the early years, Jinnah joined the Indian National Congress and worked for Hindu-Muslim unity. He was admired as an ambassador of unity and believed both communities could live together peacefully.",
        "With time, Jinnah realized that Muslims were being ignored in Indian politics. He left the Congress and joined the All India Muslim League, where he worked to protect Muslim rights and strengthen their political voice.",
        "Jinnah strongly believed that Hindus and Muslims were two separate nations with distinct cultures, religions, and values. This belief formed the basis of the demand for a separate homeland for Muslims.",
        "Under Jinnah’s leadership, the Muslim League became a powerful movement. He led Muslims with courage and determination, demanding a separate homeland where they could freely practice their religion and culture. This struggle finally resulted in the creation of Pakistan on August 14, 1947.",
        "After independence, Jinnah became the first Governor-General of Pakistan. He worked tirelessly to establish the foundations of the new nation, focusing on administration, law, education, and economic development.",
        "Jinnah’s guiding principles were Unity, Faith, and Discipline. He believed in democracy, justice, equal rights for all citizens, and the importance of education in nation-building.",
        "Despite his efforts, Jinnah faced many challenges, including limited resources, refugee crises, and political instability. However, his determination and leadership helped Pakistan survive its difficult early years.",
        "Jinnah’s health deteriorated soon after independence, but he continued to serve Pakistan until his last breath. He passed away on September 11, 1948, just a year after Pakistan’s creation.",
        "Jinnah is remembered as the Father of the Nation. His honesty, dedication, and leadership continue to inspire generations of Pakistanis. Without his vision and struggle, Pakistan would not exist today.",
        "Quaid-e-Azam Muhammad Ali Jinnah was not only a leader but a nation-builder. His life teaches us discipline, determination, and faith in one’s goals. He truly changed the course of history by creating Pakistan for the Muslims of the subcontinent.",
    ],
    "World": [
        "The world is the collective home of all human beings, cultures, and civilizations.",
        "It is a place of diversity, where millions of species coexist and ecosystems thrive.",
        "Throughout history, the world has witnessed the rise and fall of civilizations, scientific discoveries, and cultural revolutions.",
        "The modern world is connected through globalization, technology, and communication, making it a global village.",
        "Despite progress, the world also faces challenges such as poverty, climate change, and conflicts.",
    ],
    "Sea": [
        "The sea covers more than 70% of the Earth’s surface and is vital for life.",
        "It is home to countless species, from tiny plankton to massive whales.",
        "Seas provide food, trade routes, and regulate the Earth’s climate.",
        "They inspire poets, writers, and explorers with their beauty and mystery.",
        "However, pollution and overfishing threaten marine ecosystems, making their protection crucial.",
    ],
    "Earth": [
        "Earth is the only known planet that sustains life.",
        "It has a perfect balance of land, water, and atmosphere that makes living possible.",
        "The Earth is home to diverse ecosystems such as forests, deserts, oceans, and mountains.",
        "It provides natural resources like minerals, water, and fertile soil for human survival.",
        "Protecting Earth from pollution, deforestation, and climate change is the responsibility of humanity.",
    ],
    "Water": [
        "Water is the essence of life and a fundamental human need.",
        "It makes up about 70% of the human body and covers most of the Earth’s surface.",
        "Rivers, lakes, and oceans sustain agriculture, industry, and drinking supplies.",
        "Civilizations throughout history have flourished around water sources.",
        "Scarcity of clean water is a global concern that requires urgent solutions.",
    ],
    "Sky": [
        "The sky is a vast expanse that surrounds the Earth, filled with clouds, stars, and the sun.",
        "It changes its colors throughout the day, from dawn’s golden light to the deep blue of noon and the red of sunset.",
        "At night, the sky becomes a window to the universe, displaying stars, planets, and galaxies.",
        "The sky has inspired poets, philosophers, and scientists for centuries.",
        "It also plays a role in weather, climate, and the cycle of life on Earth.",
    ],
    "Universe": [
        "The universe is everything that exists, including galaxies, stars, planets, and all forms of matter and energy.",
        "It is believed to have originated from the Big Bang around 13.8 billion years ago.",
        "The universe is vast, with billions of galaxies and possibly trillions of stars.",
        "Scientists explore the universe to understand its origin, structure, and future.",
        "Its mysteries continue to inspire human curiosity and scientific exploration.",
    ],
    "Moon": [
        "The moon is Earth’s only natural satellite.",
        "01-#######It influences tides, stabilizes Earth’s rotation, and brightens the night sky.",
        "02-#######Humans first landed on the moon in 1969, marking a milestone in space exploration.",
        "03-#######In many cultures, the moon symbolizes beauty, mystery, and romance.",
        "04-#######Future space missions may establish human bases on the moon for research and exploration.",
    ],
    "Sun": [
        "The sun is the closest star to Earth and the center of our solar system.",
        "It provides light, heat, and energy necessary for life on Earth.",
        "The sun’s gravitational pull keeps planets in orbit.",
        "Solar energy is increasingly being used as a renewable source of power.",
        "Without the sun, life on Earth would not exist.",
    ],
}
